server:
  port: 8083
spring:
  application:
    name: takeout
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/takeout?characterEncoding=utf-8&&serverTimezone=UTC&&useSSL=false
    username: root
    password: xqp
#  shardingsphere:
#    datasource:
#      names: master,slave
#      master:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.80.130.100:3306/takeout?characterEncoding=utf-8&&useSSL=false
#        username: root
#        password: xqp
#      slave:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://192.168.80.128.101:3306/takeout?characterEncoding=utf-8&&useSSL=false
#        username: root
#        password: xqp
#    masterslave:
#      load-balance-algorithm-type: round_robin
#      name: dataSource
#      master-data-source-name: master
#      slave-data-source-names: slave
#    props:
#      sql:
#        show: true
#  main:
#    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1
    # 数据库索引 默认0
    database: 0
    port: 6379
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
takeout:
  path: D:\fileSave\
